'use client'

import Link from 'next/link'
import { ArrowLeft, ArrowRight, BookOpen, Search } from 'lucide-react'
import { useState } from 'react'
import { registrarInstructors } from '@/lib/registrar-data'

export default function SubjectLoadsPage() {
  const [query, setQuery] = useState('')
  const filtered = registrarInstructors.filter(x => `${x.name} ${x.id} ${x.department}`.toLowerCase().includes(query.toLowerCase()))
  return <main className="min-h-screen bg-muted/40 px-4 py-8 text-foreground sm:px-6 lg:px-10"><div className="mx-auto max-w-5xl"><Link href="/admin" className="inline-flex items-center gap-2 text-sm font-semibold text-navy"><ArrowLeft className="h-4 w-4"/> Back to registrar</Link><div className="mt-7 flex items-start gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-gold text-navy-dark"><BookOpen className="h-6 w-6"/></div><div><p className="text-xs font-bold uppercase tracking-[.2em] text-gold-dark">Registrar management</p><h1 className="mt-1 font-serif text-3xl font-bold text-navy">Subject loads</h1><p className="mt-2 text-sm text-muted-foreground">Search an instructor to view and assign their teaching loads.</p></div></div><div className="mt-8 flex items-center gap-3 rounded-xl border border-border bg-background px-4 py-3 shadow-sm"><Search className="h-4 w-4 text-muted-foreground"/><input aria-label="Search instructors" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by instructor name, ID, or department..." className="w-full bg-transparent text-sm outline-none"/></div><div className="mt-5 grid gap-4 md:grid-cols-2">{filtered.map(x=><Link key={x.id} href={`/admin/instructors/${x.id}/loads`} className="group rounded-2xl border border-border bg-background p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-gold hover:shadow-md"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-navy text-sm font-bold text-gold">{x.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</div><div><h2 className="font-serif text-lg font-bold text-navy">{x.name}</h2><p className="text-xs text-muted-foreground">{x.id} · {x.department}</p></div></div><ArrowRight className="h-5 w-5 text-gold-dark transition group-hover:translate-x-1"/></div><div className="mt-5 flex items-center justify-between border-t border-border pt-4"><span className="text-xs text-muted-foreground">Current assigned loads</span><span className="rounded-full bg-accent px-3 py-1 text-xs font-bold text-navy">{x.loads} subjects</span></div></Link>)}</div>{filtered.length===0&&<div className="mt-5 rounded-xl border border-dashed border-border bg-background p-10 text-center text-sm text-muted-foreground">No instructors match your search.</div>}</div></main>
}
