'use client'

import { useMemo, useState } from 'react'
import Image from 'next/image'
import { ArrowRight, Mail, MapPin, Search, SlidersHorizontal, Users } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { departments, facultyProfiles } from '@/lib/faculty-data'

export function FacultyDirectory() {
  const [query, setQuery] = useState('')
  const [department, setDepartment] = useState(departments[0])
  const filtered = useMemo(() => facultyProfiles.filter((person) => {
    const matchesQuery = `${person.name} ${person.department} ${person.credentials}`.toLowerCase().includes(query.toLowerCase())
    return matchesQuery && (department === departments[0] || person.department === department)
  }), [query, department])

  return <main className="min-h-screen bg-muted/30">
    <section className="bg-navy-dark text-primary-foreground"><div className="mx-auto max-w-7xl px-4 py-16 md:px-6 md:py-24"><p className="mb-4 text-sm font-bold uppercase tracking-[0.22em] text-gold">Meet the people behind the mission</p><h1 className="max-w-3xl font-serif text-4xl font-bold leading-tight md:text-6xl">Our faculty brings knowledge into action.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-primary-foreground/75 md:text-lg">Dedicated educators, practitioners, and mentors helping Loreto learners grow with competence, character, and confidence.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild className="bg-gold text-navy-dark hover:bg-gold-dark"><a href="/faculty-portal">Faculty Portal <ArrowRight className="ml-2 h-4 w-4" /></a></Button><span className="inline-flex items-center gap-2 px-3 py-2 text-sm text-primary-foreground/70"><Users className="h-4 w-4 text-gold" /> {facultyProfiles.length} faculty profiles</span></div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-10 md:px-6"><div className="mb-8 flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-gold-dark">Faculty directory</p><h2 className="mt-2 font-serif text-3xl font-bold text-navy">Find a faculty member</h2></div><div className="flex flex-col gap-3 sm:flex-row"><label className="relative"><span className="sr-only">Search faculty</span><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search by name or expertise" className="h-10 w-full rounded-md border border-border bg-background pl-9 pr-3 text-sm outline-none ring-gold focus:ring-2 sm:w-72" /></label><label className="relative"><SlidersHorizontal className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><span className="sr-only">Filter by department</span><select value={department} onChange={(e) => setDepartment(e.target.value)} className="h-10 w-full appearance-none rounded-md border border-border bg-background pl-9 pr-8 text-sm outline-none sm:w-56">{departments.map((item) => <option key={item}>{item}</option>)}</select></label></div></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{filtered.map((person) => <article key={person.email} className="group border border-border bg-background p-6 shadow-sm transition-shadow hover:shadow-md"><div className="flex items-start gap-4"><div className="flex h-16 w-16 shrink-0 items-center justify-center overflow-hidden rounded-full bg-navy text-lg font-bold text-gold">{person.initials}</div><div><h3 className="font-serif text-xl font-bold text-navy">{person.name}</h3><p className="text-sm font-semibold text-gold-dark">{person.title}</p><p className="mt-1 text-xs text-muted-foreground">{person.department}</p></div></div><p className="mt-5 border-t border-border pt-4 text-sm leading-6 text-muted-foreground">{person.credentials}</p><div className="mt-5 space-y-2 text-sm text-foreground/75"><p className="flex items-center gap-2"><MapPin className="h-4 w-4 text-gold-dark" />{person.office}</p><a href={`mailto:${person.email}`} className="flex items-center gap-2 hover:text-navy"><Mail className="h-4 w-4 text-gold-dark" />{person.email}</a></div></article>)}</div>{filtered.length === 0 && <div className="border border-dashed border-border bg-background p-12 text-center text-muted-foreground">No faculty members matched your search.</div>}</section>
    <section className="bg-gold/15"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-4 py-10 md:flex-row md:items-center md:justify-between md:px-6"><div><h2 className="font-serif text-2xl font-bold text-navy">Faculty members</h2><p className="mt-1 text-sm text-foreground/70">Need assistance with a course or academic concern?</p></div><Button asChild className="w-fit bg-navy text-primary-foreground hover:bg-navy-light"><a href="mailto:info@colegiodeloreto.edu.ph">Contact the Faculty Office <Mail className="ml-2 h-4 w-4" /></a></Button></div></section>
  </main>
}
