'use client'

import Link from 'next/link'
import { ArrowLeft, Check, UserPlus } from 'lucide-react'
import { useState } from 'react'

const input = 'h-11 w-full rounded-lg border border-border bg-background px-3 text-sm outline-none ring-gold focus:ring-2'
const label = 'flex flex-col gap-2 text-sm font-semibold text-navy'

export default function AddInstructorPage() {
  const [saved, setSaved] = useState(false)
  if (saved) return <main className="min-h-screen bg-muted/40 px-4 py-10 sm:px-6"><div className="mx-auto max-w-2xl rounded-2xl border border-gold/50 bg-accent p-10 text-center"><Check className="mx-auto h-12 w-12 rounded-full bg-gold p-3 text-navy-dark"/><h1 className="mt-5 font-serif text-3xl font-bold text-navy">Instructor profile staged</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">The demo profile is ready. Add teaching assignments separately from Subject Loads.</p><div className="mt-6 flex justify-center gap-3"><Link href="/admin" className="rounded-lg border border-navy px-4 py-2.5 text-sm font-bold text-navy">Back to registrar</Link><Link href="/admin/subject-loads" className="rounded-lg bg-navy px-4 py-2.5 text-sm font-bold text-primary-foreground">Assign subject loads</Link></div></div></main>
  return <main className="min-h-screen bg-muted/40 px-4 py-8 text-foreground sm:px-6 lg:px-10"><div className="mx-auto max-w-4xl"><Link href="/admin" className="inline-flex items-center gap-2 text-sm font-semibold text-navy hover:text-gold-dark"><ArrowLeft className="h-4 w-4"/> Back to registrar</Link><div className="mt-7 flex items-start gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-gold text-navy-dark"><UserPlus className="h-6 w-6"/></div><div><p className="text-xs font-bold uppercase tracking-[.2em] text-gold-dark">Registrar management · Demo form</p><h1 className="mt-1 font-serif text-3xl font-bold text-navy">Add instructor profile</h1><p className="mt-2 text-sm text-muted-foreground">Create the instructor record first. Subject assignments are managed separately.</p></div></div><form onSubmit={e=>{e.preventDefault();setSaved(true)}} className="mt-8 rounded-2xl border border-border bg-background p-6 shadow-sm"><h2 className="font-serif text-xl font-bold text-navy">Faculty information</h2><p className="mt-1 text-xs text-muted-foreground">Identity, department, and academic credentials only.</p><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className={label}>First name<input required className={input}/></label><label className={label}>Last name<input required className={input}/></label><label className={label}>Faculty ID<input required placeholder="CDL-FAC-000" className={input}/></label><label className={label}>Email address<input required type="email" className={input}/></label><label className={label}>Department<select className={input}><option>College of Business</option><option>College of Education</option><option>College of Public Administration</option><option>College of Tourism</option></select></label><label className={label}>Specialty<input className={input} placeholder="e.g. Agricultural economics"/></label><label className={label}>Bachelor&apos;s degree<input className={input}/></label><label className={label}>Master&apos;s degree<input className={input}/></label><label className={label}>Doctorate<input className={input}/></label><label className={label}>Employment status<select className={input}><option>Full-time</option><option>Part-time</option><option>Visiting faculty</option></select></label></div><div className="mt-7 flex flex-col justify-end gap-3 border-t border-border pt-5 sm:flex-row"><Link href="/admin" className="rounded-lg border border-border px-4 py-2.5 text-center text-sm font-bold text-navy">Cancel</Link><button type="submit" className="rounded-lg bg-navy px-5 py-2.5 text-sm font-bold text-primary-foreground hover:bg-navy-light">Save instructor profile</button></div></form></div></main>
}
