'use client'

import Link from 'next/link'
import { ArrowLeft, Check, UserPlus } from 'lucide-react'
import { useState } from 'react'
import { registrarPrograms, registrarSections } from '@/lib/registrar-data'

const inputClass = 'h-11 w-full rounded-lg border border-border bg-background px-3 text-sm outline-none ring-gold focus:ring-2'
const labelClass = 'flex flex-col gap-2 text-sm font-semibold text-navy'

export default function AddStudentPage() {
  const [saved, setSaved] = useState(false)
  function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaved(true) }
  return <main className="min-h-screen bg-muted/40 px-4 py-8 text-foreground sm:px-6 lg:px-10">
    <div className="mx-auto max-w-5xl">
      <Link href="/admin" className="inline-flex items-center gap-2 text-sm font-semibold text-navy hover:text-gold-dark"><ArrowLeft className="h-4 w-4" /> Back to registrar</Link>
      <div className="mt-7 flex items-start gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-gold text-navy-dark"><UserPlus className="h-6 w-6" /></div><div><p className="text-xs font-bold uppercase tracking-[.2em] text-gold-dark">Registrar management · Demo form</p><h1 className="mt-1 font-serif text-3xl font-bold text-navy">Add student</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Create a student record, assign an academic placement, and prepare portal credentials.</p></div></div>
      {saved ? <div className="mt-8 rounded-2xl border border-gold/50 bg-accent p-8 text-center"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-gold text-navy-dark"><Check className="h-6 w-6" /></div><h2 className="mt-4 font-serif text-2xl font-bold text-navy">Student record staged</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-muted-foreground">Demo mode saved this record for review. Connect the registrar database later to persist it permanently.</p><button onClick={() => setSaved(false)} className="mt-5 rounded-lg bg-navy px-4 py-2.5 text-sm font-bold text-primary-foreground">Add another student</button></div> : <form onSubmit={submit} className="mt-8 grid gap-5 lg:grid-cols-[1fr_320px]">
        <div className="rounded-2xl border border-border bg-background p-6 shadow-sm"><h2 className="font-serif text-xl font-bold text-navy">Student information</h2><p className="mt-1 text-xs text-muted-foreground">Required identity and enrollment details.</p><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className={labelClass}>First name<input required className={inputClass} placeholder="Maria Clara" /></label><label className={labelClass}>Last name<input required className={inputClass} placeholder="Santos" /></label><label className={labelClass}>Student ID<input required className={inputClass} placeholder="2026-00145" /></label><label className={labelClass}>Date of birth<input type="date" required className={inputClass} /></label><label className={labelClass}>Email address<input type="email" required className={inputClass} placeholder="student@email.com" /></label><label className={labelClass}>Mobile number<input className={inputClass} placeholder="09XX XXX XXXX" /></label></div><div className="mt-8 border-t border-border pt-6"><h2 className="font-serif text-xl font-bold text-navy">Academic placement</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><label className={labelClass}>Program<select required className={inputClass} defaultValue=""><option value="" disabled>Select program</option>{registrarPrograms.map(x => <option key={x}>{x}</option>)}</select></label><label className={labelClass}>Section<select required className={inputClass} defaultValue=""><option value="" disabled>Select section</option>{registrarSections.map(x => <option key={x.name}>{x.name}</option>)}</select></label><label className={labelClass}>Year level<select className={inputClass} defaultValue="1st Year"><option>1st Year</option><option>2nd Year</option><option>3rd Year</option><option>4th Year</option></select></label><label className={labelClass}>Enrollment status<select className={inputClass} defaultValue="Enrolled"><option>Enrolled</option><option>For evaluation</option><option>On leave</option></select></label></div></div></div>
        <div className="flex h-fit flex-col gap-5"><div className="rounded-2xl border border-border bg-background p-6 shadow-sm"><h2 className="font-serif text-xl font-bold text-navy">Portal credentials</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">These demo credentials will be used for student portal access.</p><div className="mt-5 flex flex-col gap-5"><label className={labelClass}>Portal username<input required className={inputClass} placeholder="2026-00145" /></label><label className={labelClass}>Temporary password<input required type="password" className={inputClass} placeholder="Create password" /></label><label className="flex items-center gap-2 text-xs text-muted-foreground"><input type="checkbox" defaultChecked className="accent-[var(--gold)]" /> Send welcome instructions</label></div></div><div className="rounded-xl border border-gold/40 bg-accent p-4 text-xs leading-5 text-muted-foreground"><span className="font-bold text-navy">Demo mode:</span> No real account or student record is created yet.</div><button className="h-11 rounded-lg bg-gold px-4 text-sm font-bold text-navy-dark transition hover:bg-gold-dark">Save student record <Check className="ml-2 inline h-4 w-4" /></button></div>
      </form>}
    </div>
  </main>
}
